#!/usr/bin/env python3
"""Generate the compiled Vial keymap from a KLAW Vial dump.

    tools/gen_keymap.py [reference/klaw_vial.json]

Writes keyboards/klaw/keymaps/vial/keymap.c (layers, encoder map, layer
names, Chordal Hold handedness) and vial_defaults.h (tap dances, combos, key
overrides, macros, QMK settings). The firmware seeds the defaults into Vial's
storage whenever it finds that storage reset, so a keyboard flashed with a
firmware built on another day keeps its configuration. The dump comes from
tools/vial_dump.py. The QMK keycode tables are taken from the vial-qmk
checkout next to this repository.
"""
import json, os, shutil, struct, sys, pathlib
try:
    import hjson  # noqa: F401, needed by the QMK keycode tables
except ImportError:
    # rerun under the interpreter of the qmk CLI, whose environment has it
    qmk_cli = shutil.which("qmk")
    interpreter = open(qmk_cli).readline()[2:].strip() if qmk_cli else None
    if not interpreter or not os.path.exists(interpreter):
        raise SystemExit("needs the hjson module; install it or put the qmk CLI on PATH")
    os.execv(interpreter, [interpreter] + sys.argv)
root = pathlib.Path(__file__).resolve().parent.parent
qmk = root.parent / "vial-qmk"
sys.path.insert(0, str(qmk / "lib/python"))
os.chdir(qmk)
from qmk.keycodes import load_spec

# Shown on each half's OLED, (left, right), up to 10 characters each
LAYER_NAMES = [("ALPHA", "ALPHA"), ("NUMBER", "NAVIGATE"), ("CUT/PASTE", "CODE"), ("FUNCT", "SYMBOL")]

spec = load_spec("latest")
names = {int(k, 16): v["key"] for k, v in spec["keycodes"].items()}
for k, v in spec["keycodes"].items():
    for a in v.get("aliases", []):
        if a.startswith("KC_") and len(a) < len(names[int(k, 16)]):
            names[int(k, 16)] = a
MODS = [(0x01, "CTL"), (0x02, "SFT"), (0x04, "ALT"), (0x08, "GUI")]
LAYER_KEYS = ((0x5200, "TO", 0x20), (0x5220, "MO", 0x20), (0x5240, "DF", 0x20), (0x5260, "TG", 0x20), (0x5280, "OSL", 0x20),
              (0x52A0, "OSM", 0x20), (0x52C0, "TT", 0x20), (0x5700, "TD", 0x100), (0x7700, "MC", 0x80))

def name(kc):
    if kc in names:
        return names[kc]
    if 0x0100 <= kc <= 0x1FFF:
        mods, base = (kc >> 8) & 0x1F, name(kc & 0xFF)
        for bit, m in MODS:
            if mods & bit:
                base = f"{'R' if mods & 0x10 else 'L'}{m}({base})"
        return base
    if 0x2000 <= kc <= 0x3FFF:
        mods = (kc >> 8) & 0x1F
        parts = [f"MOD_{'R' if mods & 0x10 else 'L'}{m}" for bit, m in MODS if mods & bit]
        return f"{parts[0][4:]}_T({name(kc & 0xFF)})" if len(parts) == 1 else f"MT({' | '.join(parts)}, {name(kc & 0xFF)})"
    if 0x4000 <= kc <= 0x4FFF:
        return f"LT({(kc >> 8) & 0xF}, {name(kc & 0xFF)})"
    for base, macro, size in LAYER_KEYS:
        if base <= kc < base + size:
            return f"{macro}({kc - base})"
    return f"0x{kc:04X}"

# LAYOUT argument order: three rows of left then right keys, then the thumb
# row with both encoder pushes
ORDER = [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (4, 4), (4, 3), (4, 2), (4, 1), (4, 0),
         (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (5, 4), (5, 3), (5, 2), (5, 1), (5, 0),
         (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (6, 4), (6, 3), (6, 2), (6, 1), (6, 0),
         (3, 1), (3, 2), (3, 4), (7, 4), (7, 2), (7, 1)]

dump = json.load(open(sys.argv[1] if len(sys.argv) > 1 else root / "reference/klaw_vial.json"))
km, enc, layers = dump["keymap"], dump["encoders"], dump["layers"]
for l in range(layers):
    stray = [(r, c) for r in range(8) for c in range(5) if (r, c) not in ORDER and km[l][r][c] not in (0, 1)]
    if stray:
        print(f"warning: layer {l} has keycodes on unused matrix positions {stray}, dropped")

def cell(l, r, c):
    return f"{name(km[l][r][c]):<8}"
lines = ["// Copyright 2026 Scramble Tools", "// SPDX-License-Identifier: GPL-3.0-or-later",
         "// Generated by tools/gen_keymap.py from reference/klaw_vial.json. The tap",
         "// dances, macros and settings it refers to live in EEPROM, see the README.",
         "#include QMK_KEYBOARD_H", "", "// clang-format off",
         "const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {"]
for l in range(layers):
    lines.append(f"    [{l}] = LAYOUT(")
    for i in range(3):
        keys = ORDER[i * 10:i * 10 + 10]
        lines.append("        " + ", ".join(cell(l, *k) for k in keys[:5]) + ",                     " + ", ".join(cell(l, *k) for k in keys[5:]) + ",")
    t = [cell(l, *k) for k in ORDER[30:]]
    lines.append(f"                                   {t[0]}, {t[1]}, {t[2]},   {t[3]}, {t[4]}, {t[5]}")
    lines.append("    )" + ("," if l < layers - 1 else ""))
lines += ["};", "", "const char *layer_name_klaw(uint8_t layer, bool left) {",
          "    static const char *const names[][2] = {" + ", ".join(f'{{"{l}", "{r}"}}' for l, r in LAYER_NAMES) + "};",
          "    return layer < ARRAY_SIZE(names) ? names[layer][left ? 0 : 1] : NULL;", "}", "",
          "#ifdef ENCODER_MAP_ENABLE", "const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {"]
for l in range(layers):
    e = ", ".join(f"ENCODER_CCW_CW({name(ccw)}, {name(cw)})" for ccw, cw in enc[l])
    lines.append(f"    [{l}] = {{ {e} }},")
lines += ["};", "#endif", "",
          "#ifdef CHORDAL_HOLD",
          "// A home row mod only settles as held together with a key of the other hand.",
          "// Thumb keys and encoder pushes may be held with anything.",
          "const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM = LAYOUT(",
          "    'L', 'L', 'L', 'L', 'L',                     'R', 'R', 'R', 'R', 'R',",
          "    'L', 'L', 'L', 'L', 'L',                     'R', 'R', 'R', 'R', 'R',",
          "    'L', 'L', 'L', 'L', 'L',                     'R', 'R', 'R', 'R', 'R',",
          "                        '*', '*', '*',   '*', '*', '*'",
          ");", "#endif", "// clang-format on", "",
          "#ifndef __AVR__",
          "// Vial keeps tap dances, macros and settings only in EEPROM, which VIA wipes",
          "// when the firmware's build date changes. Seed them again after such a wipe.",
          "#include \"via.h\"", "#include \"dynamic_keymap.h\"",
          "#ifdef QMK_SETTINGS", "#include \"qmk_settings.h\"", "#endif",
          "#include \"vial_defaults.h\"", "",
          "static bool vial_storage_was_reset;", "",
          "void via_init_kb(void) {", "    vial_storage_was_reset = !via_eeprom_is_valid();", "}", "",
          "void keyboard_post_init_user(void) {",
          "    if (!vial_storage_was_reset) {", "        return;", "    }",
          "#ifdef VIAL_TAP_DANCE_ENABLE",
          "    for (uint8_t i = 0; i < ARRAY_SIZE(default_tap_dances); i++) {",
          "        dynamic_keymap_set_tap_dance(i, &default_tap_dances[i]);", "    }", "#endif",
          "#if defined(VIAL_COMBO_ENABLE) && defined(DEFAULT_COMBOS)",
          "    for (uint8_t i = 0; i < ARRAY_SIZE(default_combos); i++) {",
          "        dynamic_keymap_set_combo(default_combos[i].index, &default_combos[i].entry);", "    }", "#endif",
          "#if defined(VIAL_KEY_OVERRIDE_ENABLE) && defined(DEFAULT_KEY_OVERRIDES)",
          "    for (uint8_t i = 0; i < ARRAY_SIZE(default_key_overrides); i++) {",
          "        dynamic_keymap_set_key_override(default_key_overrides[i].index, &default_key_overrides[i].entry);", "    }", "#endif",
          "    dynamic_keymap_macro_set_buffer(0, sizeof(default_macro_buffer), (uint8_t *)default_macro_buffer);",
          "#ifdef QMK_SETTINGS",
          "    for (uint8_t i = 0; i < ARRAY_SIZE(default_settings); i++) {",
          "        qmk_settings_set(default_settings[i].qsid, default_settings[i].value, sizeof(default_settings[i].value));", "    }", "#endif",
          "}", "#endif", ""]
keymap_path = root / "keyboards/klaw/keymaps/vial/keymap.c"
keymap_path.write_text("\n".join(lines))
print(f"wrote {keymap_path.relative_to(root)} ({layers} layers)")

def entries(fmt, rows):
    return ",\n".join("    " + fmt.format(*r) for r in rows)
h = ["// Generated by tools/gen_keymap.py. Vial entries seeded after an EEPROM reset.", "#pragma once", "#include \"vial.h\"", ""]
h.append("static const vial_tap_dance_entry_t default_tap_dances[] = {")
h.append(entries("{{0x{:04X}, 0x{:04X}, 0x{:04X}, 0x{:04X}, {}}}", dump["tap_dance"])); h.append("};")
combos = [(i, c) for i, c in enumerate(dump["combo"]) if any(c)]
if combos:
    h += ["#define DEFAULT_COMBOS", "static const struct { uint8_t index; vial_combo_entry_t entry; } default_combos[] = {"]
    h.append(entries("{{{}, {{{{0x{:04X}, 0x{:04X}, 0x{:04X}, 0x{:04X}}}, 0x{:04X}}}}}", [(i, *c) for i, c in combos])); h.append("};")
overrides = [(i, k) for i, k in enumerate(dump["key_override"]) if k[0] != 0]
if overrides:
    h += ["#define DEFAULT_KEY_OVERRIDES", "static const struct { uint8_t index; vial_key_override_entry_t entry; } default_key_overrides[] = {"]
    h.append(entries("{{{}, {{0x{:04X}, 0x{:04X}, 0x{:04X}, {}, {}, {}, {}}}}}", [(i, *k) for i, k in overrides])); h.append("};")
macro = bytes.fromhex(dump["macro_buffer"]).rstrip(b"\x00") or b"\x00"
h.append("static const uint8_t default_macro_buffer[] = {")
h += ["    " + ", ".join(f"0x{b:02X}" for b in macro[i:i + 16]) + "," for i in range(0, len(macro), 16)]
h.append("};")
h.append("static const struct { uint16_t qsid; uint8_t value[28]; } default_settings[] = {")
h.append(entries("{{{}, {{{}}}}}", [(q, ", ".join(f"0x{b:02X}" for b in bytes.fromhex(v))) for q, v in dump["qmk_settings"].items()])); h.append("};")
defaults_path = root / "keyboards/klaw/keymaps/vial/vial_defaults.h"
defaults_path.write_text("\n".join(h) + "\n")
print(f"wrote {defaults_path.relative_to(root)} ({len(dump['tap_dance'])} tap dances, {len(combos)} combos, {len(overrides)} key overrides, {len(macro)} macro bytes, {len(dump['qmk_settings'])} settings)")
