// Copyright 2026 Scramble Tools
// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/gen_keymap.py from reference/klaw_vial.json. The tap
// dances, macros and settings it refers to live in EEPROM, see the README.
#include QMK_KEYBOARD_H

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_Q    , KC_W    , KC_E    , KC_R    , KC_T    ,                     KC_Y    , KC_U    , KC_I    , KC_O    , KC_P    ,
        LSFT_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LGUI_T(KC_F), KC_G    ,                     KC_H    , RGUI_T(KC_J), RCTL_T(KC_K), RALT_T(KC_L), RSFT_T(KC_SCLN),
        KC_Z    , KC_X    , KC_C    , KC_V    , KC_B    ,                     KC_N    , KC_M    , KC_COMM , KC_DOT  , KC_SLSH ,
                                   LT(3, KC_ESC), LT(2, KC_TAB), KC_MNXT ,   KC_MNXT , KC_SPC  , LT(1, KC_BSPC)
    ),
    [1] = LAYOUT(
        KC_COMM , KC_1    , KC_2    , KC_3    , LSFT(KC_EQL),                     LGUI(KC_TAB), LGUI(KC_1), LGUI(KC_2), LGUI(KC_3), LGUI(KC_4),
        KC_0    , KC_4    , KC_5    , KC_6    , KC_MINS ,                     KC_LEFT , RGUI_T(KC_DOWN), RCTL_T(KC_UP), RALT_T(KC_RGHT), KC_RSFT ,
        KC_DOT  , KC_7    , KC_8    , KC_9    , KC_EQL  ,                     TD(20)  , TD(21)  , TD(22)  , TD(23)  , TD(10)  ,
                                   KC_ESC  , KC_TAB  , KC_MNXT ,   KC_MNXT , TO(0)   , TO(0)   
    ),
    [2] = LAYOUT(
        QK_UNDERGLOW_TOGGLE, QK_AUDIO_TOGGLE, QK_AUDIO_CLICKY_TOGGLE, KC_CAPS , TD(12)  ,                     RSFT(KC_QUOT), RSFT(KC_9), RSFT(KC_0), RSFT(KC_MINS), RSFT(KC_3),
        KC_LSFT , KC_LALT , KC_LCTL , KC_LGUI , LGUI(KC_V),                     KC_QUOT , RSFT(KC_LBRC), RSFT(KC_RBRC), KC_MINS , KC_EQL  ,
        KC_NO   , LGUI(KC_ESC), LGUI(LSFT(KC_SPC)), LGUI(KC_SPC), LGUI(KC_Z),                     KC_GRV  , KC_LBRC , KC_RBRC , RSFT(KC_GRV), KC_BSLS ,
                                   TO(1)   , KC_NO   , KC_MNXT ,   KC_MNXT , KC_ENT  , KC_DEL  
    ),
    [3] = LAYOUT(
        KC_F10  , KC_F1   , KC_F2   , KC_F3   , KC_VOLU ,                     RSFT(KC_2), RSFT(KC_6), RSFT(KC_4), RSFT(KC_1), RSFT(KC_3),
        TD(16)  , TD(17)  , TD(18)  , TD(19)  , TD(13)  ,                     RSFT(KC_3), RSFT(KC_EQL), RSFT(KC_8), RSFT(KC_7), KC_EQL  ,
        KC_F12  , KC_F7   , KC_F8   , KC_F9   , TD(30)  ,                     RSFT(KC_5), KC_MINS , KC_SLSH , RSFT(KC_BSLS), KC_BSLS ,
                                   KC_NO   , KC_NO   , KC_MNXT ,   KC_MNXT , KC_SPC  , KC_BSPC 
    )
};

const char *layer_name_klaw(uint8_t layer, bool left) {
    static const char *const names[][2] = {{"ALPHA", "ALPHA"}, {"NUMBER", "NAVIGATE"}, {"CUT/PASTE", "CODE"}, {"FUNCT", "SYMBOL"}};
    return layer < ARRAY_SIZE(names) ? names[layer][left ? 0 : 1] : NULL;
}

#ifdef ENCODER_MAP_ENABLE
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = { ENCODER_CCW_CW(KC_VOLU, KC_VOLD), ENCODER_CCW_CW(KC_VOLU, KC_VOLD) },
    [1] = { ENCODER_CCW_CW(KC_VOLU, KC_VOLD), ENCODER_CCW_CW(KC_VOLU, KC_VOLD) },
    [2] = { ENCODER_CCW_CW(KC_KB_VOLUME_UP, KC_VOLD), ENCODER_CCW_CW(KC_KB_VOLUME_UP, KC_VOLD) },
    [3] = { ENCODER_CCW_CW(KC_VOLU, KC_VOLD), ENCODER_CCW_CW(KC_VOLU, KC_VOLD) },
};
#endif

#ifdef CHORDAL_HOLD
// A home row mod only settles as held together with a key of the other hand.
// Thumb keys and encoder pushes may be held with anything.
const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM = LAYOUT(
    'L', 'L', 'L', 'L', 'L',                     'R', 'R', 'R', 'R', 'R',
    'L', 'L', 'L', 'L', 'L',                     'R', 'R', 'R', 'R', 'R',
    'L', 'L', 'L', 'L', 'L',                     'R', 'R', 'R', 'R', 'R',
                        '*', '*', '*',   '*', '*', '*'
);
#endif
// clang-format on

#ifndef __AVR__
// Vial keeps tap dances, macros and settings only in EEPROM, which VIA wipes
// when the firmware's build date changes. Seed them again after such a wipe.
#include "via.h"
#include "dynamic_keymap.h"
#ifdef QMK_SETTINGS
#include "qmk_settings.h"
#endif
#include "vial_defaults.h"

static bool vial_storage_was_reset;

void via_init_kb(void) {
    vial_storage_was_reset = !via_eeprom_is_valid();
}

void keyboard_post_init_user(void) {
    if (!vial_storage_was_reset) {
        return;
    }
#ifdef VIAL_TAP_DANCE_ENABLE
    for (uint8_t i = 0; i < ARRAY_SIZE(default_tap_dances); i++) {
        dynamic_keymap_set_tap_dance(i, &default_tap_dances[i]);
    }
#endif
#if defined(VIAL_COMBO_ENABLE) && defined(DEFAULT_COMBOS)
    for (uint8_t i = 0; i < ARRAY_SIZE(default_combos); i++) {
        dynamic_keymap_set_combo(default_combos[i].index, &default_combos[i].entry);
    }
#endif
#if defined(VIAL_KEY_OVERRIDE_ENABLE) && defined(DEFAULT_KEY_OVERRIDES)
    for (uint8_t i = 0; i < ARRAY_SIZE(default_key_overrides); i++) {
        dynamic_keymap_set_key_override(default_key_overrides[i].index, &default_key_overrides[i].entry);
    }
#endif
    dynamic_keymap_macro_set_buffer(0, sizeof(default_macro_buffer), (uint8_t *)default_macro_buffer);
#ifdef QMK_SETTINGS
    for (uint8_t i = 0; i < ARRAY_SIZE(default_settings); i++) {
        qmk_settings_set(default_settings[i].qsid, default_settings[i].value, sizeof(default_settings[i].value));
    }
#endif
}
#endif
